check if aura installed

diff --git a/aur-packages b/aur-packages
--- a/aur-packages
+++ b/aur-packages
@@ -1,20 +1,21 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+# Install aura if not installed
+if ! command -v aura &> /dev/null; then
+    # AUR install
+    cd /tmp
+    git clone https://aur.archlinux.org/aura-bin.git
+    cd aura-bin
+    makepkg -si --noconfirm
+    cd ~
+    # Clean up the build directory
+    rm -rf /tmp/aura-bin
+fi
 
-# AUR install
-cd /tmp
-git clone https://aur.archlinux.org/aura-bin.git
-cd aura-bin
-makepkg -si --noconfirm
-cd ~
-# Clean up the build directory
-rm -rf /tmp/aura-bin
-
-
-# AUR packages
+# Install AUR packages
 aura -A --noconfirm brave-origin-bin kanata-bin pcloud-drive \
-ttf-noto-emoji-monochrome einfach-icon-theme einfach-grub-theme
+    ttf-noto-emoji-monochrome einfach-icon-theme einfach-grub-theme
 
 
 # Fnm install (Currently Commmented)
